# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [11]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [15]:

sum_list = [a + b for a, b in zip(l_1, l_2)]
print(sum_list)

l_A = [2, 3, 4]
l_B = [1, 5, 2]

listadd = []

def add(arrA, arrB):
    for x in range(0, len(arrA)):
        listadd.append(arrA[x] + arrB[x])
    return listadd

print('Addition: ', add(l_A, l_B))

[5, 7, 9]
Addition:  [3, 8, 6]


#### Importing

In [16]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [17]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


###### - np.zeros()

In [19]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeroes = np.zeros((4,3))
print(arr_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


###### - np.ones()

In [20]:
arr_ones = np.ones((3,3),int)
arr_ones
# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [21]:
arr_range = np.arange(1,12)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### - Making Lists into NDArrays

In [23]:
list_1 = [7,8,9]

arr_list = np.array(list_1)
arr_list

array([7, 8, 9])

#### Performing Calculations on NDArrays

###### - Summation

In [24]:
arr1 = np.array([5,10,15,20,25])
arr2 = np.array([10,20,30,40,50])

result_sum = arr1 + arr2
print(result_sum)

[15 30 45 60 75]


###### - Difference

In [25]:
result_diff = arr2 - arr1
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [26]:
result_mul = arr2 * arr1
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [27]:
result_quo = arr1 / arr2
result_quo

array([0.5, 0.5, 0.5, 0.5, 0.5])

#### Modulo

In [29]:
result_mod = arr2 % arr1
result_mod

array([0, 0, 0, 0, 0])

#### Floor Division

In [30]:
result_floor = arr2 // arr1
result_floor

array([2, 2, 2, 2, 2])

#### Numpy Subsetting

In [38]:
print(result_mul)
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings[test_ndStrings == 'Bob'])
test_ndStrings[np.char.startswith(test_ndStrings, 'B')]


# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[  50  200  450  800 1250]
[ True  True  True  True False]
[ 50 200 450 800]
['Bob']


array(['Bob', 'Barb'], dtype='<U8')

#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [44]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
M
print(M[1][1])
# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(f"NDArray Structure:\n {ND_M}")

4
NDArray Structure:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [45]:
print(f"Getting the Middle element of the matrix: {ND_M[1,1]}")

Getting the Middle element of the matrix: 4


#### Assigning Values in NDArrays

In [46]:
ND_M[1,1] = 8
ND_M

array([[0, 1, 2],
       [3, 8, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [47]:
# usind the .dtype() method
nd_type = ND_M.dtype
nd_type

dtype('int64')

#### Altering NDArray Type

In [49]:
result_dt = nd_type
print(f"Type before: {result_dt}")
changed_M = ND_M.astype(np.float32)
print(f"Type after: {changed_M.dtype}")

print(changed_M)

Type before: int64
Type after: float32
[[0. 1. 2.]
 [3. 8. 5.]
 [6. 7. 8.]]


In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [50]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape

# print(type(result_changed.shape))
print(changed_M.shape)

(3, 3)


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [51]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(changed_M.reshape((1,9)))

[[0. 1. 2. 3. 8. 5. 6. 7. 8.]]


In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [65]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""


matrix = np.array(range(0,16)).reshape((4,4)).astype(np.float32)
print(matrix)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


#### Complex Indexing & Assinging

In [67]:
M = np.zeros((6,6))
print('Resetting Matrix')
print('Before Assignment: ')
print(M)

# Set every first element in each row to 1
M[:,0] = 1
print('\n After assigning 1 to first col\n', M)
# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M[2:5,:] = 5
print('\n cols 3-5 set to 5:\n', M)

# reset the matrix back to 0
M = M * 0
print(M)

# Set the second and third columns to a number == 2
M[:,1:3] = 2
print('\n second & third cols set == 2\n', M)

# Creating a vector in numpy
x = np.arange(6)

# Reset the Matrix to 0
M*=0

# Set the first row to that range of vector numbers we just created
M[0,:] = x
print('\n assigning vector array x to the first axis', M)

#################
# M[rows,columns]
#################

Resetting Matrix
Before Assignment: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After assigning 1 to first col
 [[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

 cols 3-5 set to 5:
 [[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 second & third cols set == 2
 [[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]

 assigning vector array x to the first axis [[0. 1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [70]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v = M[:,:] = 0
print(v)

# Reset the Matrix to 0
M *= v
print(M)
M.reshape(4,9)

0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [74]:
print(result_mul)
print('\n', np.where(result_mul > 200))
print(result_mul[np.where(result_mul > 200)])
# Transform Data based on boolean mask == True

result_mul[np.where(result_mul > 200)] = 300

print(result_mul)

[  50  200  450  800 1250]

 (array([2, 3, 4]),)
[ 450  800 1250]
[ 50 200 300 300 300]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [76]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.12640014653288523
Here is a random number between 0 and 1 Million: 941266.2748313413
Here are 5 random numbers between 0 and 10: [9.92811607 7.71141224 9.42254358 9.7583981  1.51769219]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[5.88182066 7.98323022 2.21206009]
 [7.79046953 5.89475131 6.89082562]
 [7.59173204 6.82779127 4.40079236]]


## Working With CSV's

#### Imports

In [77]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [85]:
# Creating Function to open and read CSV data
def open_csv(filename, d = ','):
    #define empty list to store data
    data = []
    
    with open(filename, encoding='utf-8') as mData:
        #use the csv .reader() to create a python list
        info = csv.reader(mData, delimiter = d)

        # loop over the info and append it to the data list
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../day_1/files/boston_marathon2017_edited.csv')

print(csv_data[1:5])

[['12/30/1899 12:30:28 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:02:53 AM', '12/30/1899 12:15:25 AM', '24', '11', '7777', 'KEN', '7777', '', 'Keringet', 'KEN', '1', '1', '12/30/1899 1:04:35 AM', 'M', 'Kirui, Geoffrey', '1', '12/30/1899 2:09:37 AM', '1', '12/30/1899 12:04:57 AM', ''], ['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', '12/30/1899 2:09:58 AM', '2', '12/30/1899 12:04:58 AM', 'OR'], ['12/30/1899 12:30:29 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:16 AM', '12/30/1899 1:17:00 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:31 AM', '12/30/1899 2:03:38 AM', '12/30/1899 12:15:25 AM', '25', '23', '7828', 'JP

#### Loading a CSV's Data 

In [91]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../day_1/files/redsox_2017_hitting.txt')
print(bs2017['Name'])

# find the total hits for this year
total_hits = sum(bs2017['H'])
print(f"\n Total Hits for 2017: {total_hits}")

[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]

 Total Hits for 2017: 1459


#### Summing the top 5 hitters for HR's

In [124]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
home_run = bs2017['HR']
# print(home_run)

# Step 2
names = bs2017['Name']
# print(names)

# Step 3
new_names = []
# Step 4
# print(new_names)
new_names = names.astype('str')
# Step 5
merged = list(zip(new_names, home_run))
# print(zipped_values)

# Step 6
merged.sort(key = lambda x: x[1], reverse=True)
print(merged[:5])


[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>